name: color
channels:
  - conda-forge
dependencies:
  - python=3.6.9
  - cudatoolkit=10.0
  - psutil
  - opencv=3.4.2
  - pyyaml>=5.1
  - pillow<7.0
  - pip
  - pip:
    - tensorflow-gpu==2.0.0
    - tensorflow-addons==0.6.0
    - matplotlib
    - scipy==1.1.0
    - requests    
    - pypng
